#ifndef BLACKBIRD_LINGUIST_H_
#define BLACKBIRD_LINGUIST_H_

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Potential errors returned from the Linguist C-API.
enum LinguistError {
    LinguistError_None,
    LinguistError_NotFound,
    LinguistError_Panic,
    LinguistError_IllegalState,
    LinguistError_InvalidUtf8,
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Check if the path and content is considered indexable for code search.
//
// If successful the out-parameter `indexable` will be set. If `indexable` is `false`, a pointer to a new
// null-terminated UTF-8 string is stored in the out-parameter `*reason`. The caller is responsible
// for freeing the string by calling [`linguist_cstring_free`].
//
// # Safety
//
// `path` must be a valid pointer to UTF-8 encoded, null-terminated string. `content` must be a
// valid pointer to a UTF-8 encoded string of length: `content_len`.
enum LinguistError linguist_is_indexable(const char *path, const uint8_t *content, size_t content_len, bool *indexable, char **reason);

// Free a CString returned by [`linguist_is_indexable`].
//
// # Safety
//
// `ptr` must be a pointer produced by a successful call to `linguist_is_indexable` and not already freed.
enum LinguistError linguist_cstring_free(char *ptr);

// Convert a Linguist language ID to a language name, if possible.
//
// If successful, set `language_name` and `language_name_len` with bytes
// representing the name as a valid UTF-8 encoded string.
//
// If the ID cannot be translated to a name, an error will be returned and the
// out parameters will be left unmodified.
//
// # Safety
//
// The pointers must be valid and non-null.
enum LinguistError get_language_name(uint32_t id, const char **language_name, size_t *language_name_len);

// Convert a Linguist language alias to a language ID, if possible.
//
// If successful, set `id` to the language ID.
//
// If the alias cannot be translated to a name, an error will be returned.
//
// # Safety
//
// `alias` must be a valid pointer to a UTF-8 encoded, null-terminated string.
enum LinguistError get_language_by_alias(const char *alias, uint32_t *id);

// Convert a Linguist language ID to a language color, if possible.
//
// If successful, set `language_color` and `language_color_len` with bytes
// representing the color as a valid UTF-8 encoded string. If no color is
// defined, `language_color` and `language_color_len` will not be modified.
//
// If the ID cannot be translated to a color, an error will be returned.
//
// # Safety
//
// The pointers must be valid and non-null.
enum LinguistError get_language_color(uint32_t id, const char **language_color, size_t *language_color_len);

// Convert a Linguist language ID to a TextMate scope, if possible.
//
// If successful, set `language_tm_scope` and `language_tm_scope_len` with
// bytes representing the TextMate scope as a valid UTF-8 encoded string. If
// unsuccessful, the pointers will not be modified.
//
// Note that Linguist's data files define `"none"` as the `tm_scope` value when
// none is defined for a language.
//
// If the ID cannot be translated to a TextMate scope, an error will be
// returned.
//
// # Safety
//
// The pointers must be valid and non-null.
enum LinguistError get_language_tm_scope(uint32_t id, const char **language_tm_scope, size_t *language_tm_scope_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BLACKBIRD_LINGUIST_H_ */
