package linguist

import (
	"fmt"
	"math"
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_LinguistViaCGO(t *testing.T) {
	var tests = []struct {
		id      uint32
		name    string
		color   string
		tmScope string
	}{
		{
			id:      327,
			name:    "Rust",
			color:   "#dea584",
			tmScope: "source.rust",
		},
		{
			id:      132,
			name:    "Go",
			color:   "#00ADD8",
			tmScope: "source.mligo",
		},
		{
			id:      326,
			name:    "Ruby",
			color:   "#701516",
			tmScope: "source.ruby",
		},
		{
			id:      379,
			name:    "Unified Parallel C",
			color:   "#4e3617",
			tmScope: "source.c",
		},
		{
			id:      512838272,
			name:    "MDX",
			color:   "#fcb32c",
			tmScope: "source.mdx",
		},
		{
			id:      987654321, // does not exist
			name:    "",
			color:   "",
			tmScope: "",
		},
		{
			id:      129,
			name:    "Gettext Catalog",
			color:   "", // no color set
			tmScope: "source.po",
		},
		{
			id:      20,
			name:    "Arc",
			color:   "#aa2afe",
			tmScope: "none",
		},
	}

	for _, test := range tests {
		t.Run(fmt.Sprintf("language %d", test.id), func(t *testing.T) {
			t.Run("GetLanguageName", func(t *testing.T) {
				name, err := GetLanguageName(test.id)
				if test.name == "" {
					require.Error(t, err)
					require.Empty(t, name)
				} else {
					require.NoError(t, err)
					require.Equal(t, test.name, name)
				}
			})

			t.Run("GetLanguageColor", func(t *testing.T) {
				color, err := GetLanguageColor(test.id)
				switch {
				case test.name == "":
					require.Error(t, err)
				case test.color == "":
					require.Empty(t, err)
					require.Empty(t, color)
				default:
					require.NoError(t, err)
					require.Equal(t, test.color, color)
				}
			})

			t.Run("GetLanguageTMScope", func(t *testing.T) {
				color, err := GetLanguageColor(test.id)
				switch {
				case test.name == "":
					require.Error(t, err)
				case test.color == "":
					require.Empty(t, err)
					require.Empty(t, color)
				default:
					require.NoError(t, err)
					require.Equal(t, test.color, color)
				}
			})
		})
	}
}

func Test_GetLanguageByAlias(t *testing.T) {
	var tests = []struct {
		alias string
		id    uint32
	}{
		{
			alias: "rs",
			id:    327,
		},
		{
			alias: "Rust",
			id:    327,
		},
		{
			alias: "SaltStack",
			id:    339,
		},
		{
			alias: "saltstate",
			id:    339,
		},
		{
			alias: "SALT", // case doesn't matter
			id:    339,
		},
		{
			alias: "does not exist",
			id:    math.MaxUint32,
		},
	}

	for _, test := range tests {
		t.Run(test.alias, func(t *testing.T) {
			id, err := GetLanguageByAlias(test.alias)
			if test.id == math.MaxUint32 {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
				require.Equal(t, test.id, id)
			}
		})
	}
}

func Test_IsIndexable(t *testing.T) {
	isIndexable, reason, err := IsIndexable("foo/bar.rs", []byte("fn main() {}"))
	require.NoError(t, err)
	require.True(t, isIndexable)
	require.Equal(t, reason, "")

	isIndexable, reason, err = IsIndexable(".gitignore", []byte(""))
	require.NoError(t, err)
	require.False(t, isIndexable)
	require.Equal(t, reason, "FilePath(GitIgnore)")

	isIndexable, reason, err = IsIndexable("test.go", []byte("Code generated by"))
	require.NoError(t, err)
	require.False(t, isIndexable)
	require.Equal(t, reason, "Content(GeneratedGo)")

	// Make sure the NULL char in the middle is OK
	isIndexable, reason, err = IsIndexable("test.go", []byte("go\x00Code generated by"))
	require.NoError(t, err)
	require.False(t, isIndexable)
	require.Equal(t, reason, "Content(GeneratedGo)")
}
